lib/sanity-api.ts, package.json, shared/components/team/membercard.tsx, yarn.lock
Made the team members images rounded and added sanity URL builder to get the image as a link from the sanity server.
Fixed un-rounded images.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Update Members 2022

lib/data/domains.ts, lib/sanity-api.ts, shared/components/team/membercard.tsx
Continuation to #49 
Made the team members images rounded and added sanity URL builder to get the image as a link from the sanity server.
Fixed un-rounded images.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Revert - Update members 2022

pages/events/index.tsx, shared/components/events/card.tsx, shared/components/events/event-details.tsx, shared/components/events/whats-new.tsx, yarn.lock
=> 🐛 event end

pages/register.tsx
Fixed Typo-error in Events Registration page for Events which have ended.
=> :bug: Fix Grammar

.env.example
Added `.env.example` file
Fixes #56
=> :memo: Add .env.example file

pages/events/[slug].tsx, pages/events/index.tsx, pages/register.tsx, utils/schema.ts
Added Dropdown for Department in `/register` page and Fixed "Register Now" Button in `/events/[slug].tsx`
Fixes #61 
https://user-images.githubusercontent.com/92621098/210271270-691df493-eb90-4c3f-a4cd-ead997d0b22c.mp4
=> Add dropdown in registration

pages/_app.tsx, pages/events/[slug].tsx, pages/events/index.tsx, pages/projects/[slug].tsx
Change Events page from SSR to SSG
=> :sparkles: SSR to SSG

.npmrc, .yarnrc, package.json
Set strict node version requirement in package.json and enforce it using .yarnrc and .npmrc
=> chore: Strict node version required

shared/components/footer.tsx
update the name, phone number and email.
'+
=> update contact details

pages/events/[slug].tsx, shared/client.ts, shared/components/events/event-prizes.tsx
Changed the name of the component from "PrizePage" to "PrizeComponent"
=> Change the name of the component

.env.example, lib/data/domains.ts, lib/sanity-api.ts, pages/projects/[slug].tsx, shared/client.ts
This PR 
- fixes build errors by making sanity project id a client env
- moves all sanity API fetches to `sanity-api.ts`
- rearranges domains in alphabetical order
=> fix: build error

pages/_app.tsx
=> update meta content

shared/components/events/card.tsx
Changed the color of the Registration button on the event's card.
'+
=> feat: update register button color

pages/404.tsx
Fix for missing background in the 404 screen
After:
Before:
Fixes #89 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
'+
=> fix: 404 background fix

pages/register/index.tsx
=> fix: add padding

pages/404.tsx, pages/register/success.tsx
Motion Img had a dot in both the files `success.tsx` and `404.tsx`
After:
Before:
Fixes # (issue)
'+
=> fix: Fixed stars background

shared/components/events/event-timeline.tsx
=> Events Timeline UI Fixes

shared/client.ts
adds apiVersion to sanityClient to remove the warning.
Fixes #105 
Please delete options that are not relevant.
=> Fixes sanity warning

pages/404.tsx, pages/_app.tsx, pages/events/index.tsx, pages/index.tsx, pages/projects.tsx, pages/register/index.tsx, pages/register/success.tsx, pages/services.tsx, pages/team/index.tsx, shared/components/home/card.tsx, shared/components/home/process.tsx, shared/components/loader.tsx
Resolves the errors in development environment.
Fixes #106 
Please delete options that are not relevant.
=> Removes Errors

lib/data/reviews.ts
updated the position of the alumni's
=> update position of alumni's

pages/team/[year].tsx
This PR fixes the title on the Team 2022 page.
@anujapandeyy and @aashvi4946
=> titles update

pages/team/data/2023.json, shared/components/navbar.tsx
Add 2023 batch data to production
'+
=> chore: add 2023 batch data
